# Generated by Django 2.1.7 on 2019-12-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionparameterbank_key_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionparameter',
            name='question_field',
        ),
    ]
